# Generated by Django 4.2.3 on 2023-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='client_last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_phone_number',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
    ]
